# Generated by Django 2.0.4 on 2018-04-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=120)),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='dv',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='rut',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
